### ISSUE TITLE
Extension for jsonl

### ISSUE THREAD

**Issue by ChrisChross** [AMDmi3/jsonslicer#51]
Hey @AMDmi3,

just wanted to ask if it is possible to extend this great package to support jsonl also?
I want to load chunks of 1000 lines in each step. 

Best regards 
Chris

**Comment by AMDmi3** [comment]
If I understand correctly which jsonl is, namely just a set of concatenated (with or without separating newlines) json objects, this should already be supported through `yajl_allow_multiple_values` argument to JsonSlicer constructor (this is documented in the README).

Note that you may not really need/gain much benefit from JsonSlicer in this case, since you already have small json objects and may just process input line by line and parse json with stock `json` module without having any big memory overhead.

**Comment by ChrisChross** [comment]
cool. thank you!
